imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    #- { resource: @HexagonalApiBundle/Resources/config/routing.xml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true


# Doctrine Configuration
doctrine:
    dbal:
        default_connection: core
        connections:
            core:
                driver:   %database_core_driver%
                host:     %database_core_host%
                port:     %database_core_port%
                dbname:   %database_core_name%
                user:     %database_core_user%
                password: %database_core_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: core
        entity_managers:
          core:
            mappings:
              Core:
                type: xml
                dir: %kernel.root_dir%/../src/Infastructure/Adapter/Repository/Doctrine/Mapping/Xml
                prefix: Hexagonal\Core\Entity

fos_rest:
    view:
        formats:
            json: true
            jsonp: true
        jsonp_handler:
            callback_param:       callback
            mime_type:            ~
        view_response_listener: force
    routing_loader:
        default_format: json

sensio_framework_extra:
    view:    { annotations: false }
